# Automatically generated by configure - do not modify
TARGET_ARCH=arm
TARGET_ARM=y
TARGET_BASE_ARCH=arm
TARGET_PHYS_ADDR_BITS=64
CONFIG_SOFTMMU=y
LIBS+=-lutil 
HWDIR=../libhw64
TARGET_XML_FILES= /home/ivan/developer/hp50g/x49gp/qemu/qemu-git/gdb-xml/arm-core.xml /home/ivan/developer/hp50g/x49gp/qemu/qemu-git/gdb-xml/arm-vfp.xml /home/ivan/developer/hp50g/x49gp/qemu/qemu-git/gdb-xml/arm-vfp3.xml /home/ivan/developer/hp50g/x49gp/qemu/qemu-git/gdb-xml/arm-neon.xml
CONFIG_SOFTFLOAT=y
CONFIG_I386_DIS=y
CONFIG_ARM_DIS=y
LDFLAGS+=
QEMU_CFLAGS+=-I$(SRC_PATH)/fpu -I$(SRC_PATH)/tcg -I$(SRC_PATH)/tcg/$(ARCH) 
