/* Automatically generated by create_config - do not modify */
#define HOST_X86_64 1
#define HOST_LONG_BITS 64
#define CONFIG_POSIX 1
#define CONFIG_LINUX 1
#define CONFIG_BDRV_WHITELIST \
    NULL
#define CONFIG_FNMATCH 1
#define QEMU_VERSION "0.12.50"
#define QEMU_PKGVERSION ""
#define CONFIG_PIPE2 1
#define CONFIG_ACCEPT4 1
#define CONFIG_BYTESWAP_H 1
#define CONFIG_IOVEC 1
#define CONFIG_PREADV 1
#define CONFIG_GCC_ATTRIBUTE_WARN_UNUSED_RESULT 1
#define CONFIG_FDATASYNC 1
